# Framewor for testing web aplications - proof of concept
# Authors:  Roman Vais <rvais@redhat.com>
#
# This is configuration file for Travis CI

dist: trusty
sudo: required

addons:
  firefox: "54.0"

language: python
python:
  - "3.6"

# before_install:
#  - 

install:
  # get gecko webdriver
  - wget -N https://github.com/mozilla/geckodriver/releases/download/v0.18.0/geckodriver-v0.18.0-linux32.tar.gz -P ~/
  - tar xvzf ~/geckodriver-v0.18.0-linux32.tar.gz -C ~/
  - rm ~/geckodriver-v0.18.0-linux32.tar.gz
  - sudo mv -f ~/geckodriver /usr/local/share/
  - sudo chmod +x /usr/local/share/geckodriver
  - sudo ln -s /usr/local/share/geckodriver /usr/local/bin/geckodriver

  # instal necessary modules for python
  - pip install -Ur requirements.txt

before_script: 
  # fake display for browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

  # setup browser settings for webtests

  - echo $(which firefox)
  - echo $(which geckodriver)
  - export BROWSER_BIN_PATH=`readlink -f $(which firefox)`
  - export DRIVER_BIN_PATH=`readlink -f $(which geckodriver)`
  - export PYTHONPATH="${PWD%/}${PYTHONPATH:+:}${PYTHONPATH:-}"

script:
  -  python webtest/webagent.py
 
