dist: trusty
sudo: required

addons:
  chrome: stable  # get stable version of chrome

language: python
python:
  - "3.6"

# before_install:
#  - 

install:
  # get chrome webdriver
  - wget -N http://chromedriver.storage.googleapis.com/2.30/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - sudo mv -f ~/chromedriver /usr/local/share/
  - sudo chmod +x /usr/local/share/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver

  # instal necessary modules for python
  - pip install -Ur requirements.txt

before_script: 
  # fake display for browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

  # setup browser settings for webtests
  - echo $(which google-chrome)
  - echo $(which chromedriver)
  - export BROWSER_BIN_PATH=`readlink $(which google-chrome)`
  - export DRIVER_BIN_PATH=`readlink $(which chromedriver)`
  - export PYTHONPATH="${PWD%/}${PYTHONPATH:+:}${PYTHONPATH:-}"

script:
  -  python webtest/webagent.py
 
